#!/bin/bash

# Upgraded by Frank Morales (frank@virtalus.com)
# Changelog:
# - Added a 2 functions (referencing IPv4 and IPv6) to make the rules persistent

source /var/lib/./onegate.sh

### Functions

# Apply iptables ipv4 rules
configure_ipv4_masquerade(){
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    echo "IPV4 MASQUERADE ENABLED VIA ETH0" >> /etc/motd
    info IPv4_MASQUERADE "IPV4 MASQUERADE ENABLED VIA ETH0" 2>/dev/null
}

# Apply iptables ipv4 rules
configure_ipv6_masquerade(){
    ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    echo "IPV6 MASQUERADE ENABLED VIA ETH0" >> /etc/motd
    info IPv6_MASQUERADE "IPV6 MASQUERADE ENABLED VIA ETH0" 2>/dev/null
}

# Make iptables ipv4 rules persistent
make_iptables_ipv4_persist(){
    filepath=/etc/iptables/rules.v4
    iptables-save > $filepath
    printf "y\n" | iptables-apply $filepath
}

# Make iptables ipv4 rules persistent
make_iptables_ipv6_persist(){
    filepath=/etc/iptables/rules.v6
    iptables-save > $filepath
    printf "y\n" | iptables-apply $filepath
}

# Get eth0 IPv4
get_first_interface_ipv4() {
    env | grep -E "^ETH0+_IP=" | cut -d '=' -f 2
}
# Get eth0 IPv6
get_first_interface_ipv6() {
    env | grep -E "^ETH0+_IP6=" | cut -d '=' -f 2
}

# Reset iptables rules
reset_iptables(){
    iptables --flush
    iptables -t nat --flush
}

create_masquerade(){
    if [ -n "${ETH0_MAC}" ]; then
        ipv4="$(get_first_interface_ipv4)"
            ipv4_private="$(echo $ipv4 | grep -E '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)')"
            #echo "ipv4 is $ipv4"
            #echo "ipv4 private is $ipv4_private"
        ipv6="$(get_first_interface_ipv6)"
            #echo "ipv6 is $ipv6"
        if [ -z "${ipv4_private}" ]; then
                configure_ipv4_masquerade
                make_iptables_ipv4_persist
        else
            echo "IPV4 MASQUERADE DISABLED" >> /etc/motd
            status IPv4_MASQUERADE DISABLED 2>/dev/null
        fi
        if [ -n "${ipv6}" ]; then
                configure_ipv6_masquerade
                make_iptables_ipv6_persist
        else
            echo "IPV6 MASQUERADE DISABLED" >> /etc/motd
            status IPv6_MASQUERADE DISABLED 2>/dev/null
        fi
    fi
}


echo "=========================MASQUERADE========================" >> /etc/motd
reset_iptables
create_masquerade
